name: method4

on:
  push:
    branches:
      - main
    paths-ignore: 
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore: 
      - '**.md'

env:
  DEVELOPER_DIR: /Applications/Xcode_13.3.1.app/Contents/Developer
  
jobs:
  test:
    runs-on:
      - macos-12

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Run toggle-software-keyboard service
      run: |
        cd toggle-software-keyboard
        swift build
        swift run &
        cd ..
        scripts/wait-for-toggle-software-keyboard-service.sh

    - name: Use hardware keyboard
      run: |
        xcodebuild -project AllTests/AllTests.xcodeproj -scheme UseHard test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13'

    - name: Test
      run: |
        xcodebuild -project AllTests/AllTests.xcodeproj -scheme SoftHardTest test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13'
